//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("smqdocModel", "GroupManager", "UserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFront.DB.UserGroup), "UserAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcFront.DB.UserAccount), true)]
[assembly: EdmRelationshipAttribute("smqdocModel", "GroupUsers", "UserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFront.DB.UserGroup), "UserAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFront.DB.UserAccount))]
[assembly: EdmRelationshipAttribute("smqdocModel", "FieldTeplateDocTemplate", "FieldTeplate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcFront.DB.FieldTemplate), "DocTemplate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcFront.DB.DocTemplate), true)]

#endregion

namespace MvcFront.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class smqdocEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new smqdocEntities object using the connection string found in the 'smqdocEntities' section of the application configuration file.
        /// </summary>
        public smqdocEntities() : base("name=smqdocEntities", "smqdocEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new smqdocEntities object.
        /// </summary>
        public smqdocEntities(string connectionString) : base(connectionString, "smqdocEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new smqdocEntities object.
        /// </summary>
        public smqdocEntities(EntityConnection connection) : base(connection, "smqdocEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserAccount> UserAccounts
        {
            get
            {
                if ((_UserAccounts == null))
                {
                    _UserAccounts = base.CreateObjectSet<UserAccount>("UserAccounts");
                }
                return _UserAccounts;
            }
        }
        private ObjectSet<UserAccount> _UserAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserGroup> UserGroups
        {
            get
            {
                if ((_UserGroups == null))
                {
                    _UserGroups = base.CreateObjectSet<UserGroup>("UserGroups");
                }
                return _UserGroups;
            }
        }
        private ObjectSet<UserGroup> _UserGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DocTemplate> DocTemplates
        {
            get
            {
                if ((_DocTemplates == null))
                {
                    _DocTemplates = base.CreateObjectSet<DocTemplate>("DocTemplates");
                }
                return _DocTemplates;
            }
        }
        private ObjectSet<DocTemplate> _DocTemplates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FieldTemplate> FieldTemplates
        {
            get
            {
                if ((_FieldTemplates == null))
                {
                    _FieldTemplates = base.CreateObjectSet<FieldTemplate>("FieldTemplates");
                }
                return _FieldTemplates;
            }
        }
        private ObjectSet<FieldTemplate> _FieldTemplates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserAccounts(UserAccount userAccount)
        {
            base.AddObject("UserAccounts", userAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserGroups(UserGroup userGroup)
        {
            base.AddObject("UserGroups", userGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DocTemplates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocTemplates(DocTemplate docTemplate)
        {
            base.AddObject("DocTemplates", docTemplate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FieldTemplates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFieldTemplates(FieldTemplate fieldTemplate)
        {
            base.AddObject("FieldTemplates", fieldTemplate);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="smqdocModel", Name="DocTemplate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DocTemplate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DocTemplate object.
        /// </summary>
        /// <param name="docteplateid">Initial value of the docteplateid property.</param>
        /// <param name="templateName">Initial value of the TemplateName property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="comment">Initial value of the Comment property.</param>
        /// <param name="lastEditDate">Initial value of the LastEditDate property.</param>
        public static DocTemplate CreateDocTemplate(global::System.Int64 docteplateid, global::System.String templateName, global::System.Int32 status, global::System.String comment, global::System.DateTime lastEditDate)
        {
            DocTemplate docTemplate = new DocTemplate();
            docTemplate.docteplateid = docteplateid;
            docTemplate.TemplateName = templateName;
            docTemplate.Status = status;
            docTemplate.Comment = comment;
            docTemplate.LastEditDate = lastEditDate;
            return docTemplate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 docteplateid
        {
            get
            {
                return _docteplateid;
            }
            set
            {
                if (_docteplateid != value)
                {
                    OndocteplateidChanging(value);
                    ReportPropertyChanging("docteplateid");
                    _docteplateid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("docteplateid");
                    OndocteplateidChanged();
                }
            }
        }
        private global::System.Int64 _docteplateid;
        partial void OndocteplateidChanging(global::System.Int64 value);
        partial void OndocteplateidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TemplateName
        {
            get
            {
                return _TemplateName;
            }
            set
            {
                OnTemplateNameChanging(value);
                ReportPropertyChanging("TemplateName");
                _TemplateName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TemplateName");
                OnTemplateNameChanged();
            }
        }
        private global::System.String _TemplateName;
        partial void OnTemplateNameChanging(global::System.String value);
        partial void OnTemplateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastEditDate
        {
            get
            {
                return _LastEditDate;
            }
            set
            {
                OnLastEditDateChanging(value);
                ReportPropertyChanging("LastEditDate");
                _LastEditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEditDate");
                OnLastEditDateChanged();
            }
        }
        private global::System.DateTime _LastEditDate;
        partial void OnLastEditDateChanging(global::System.DateTime value);
        partial void OnLastEditDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "FieldTeplateDocTemplate", "FieldTeplate")]
        public EntityCollection<FieldTemplate> FieldTeplates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FieldTemplate>("smqdocModel.FieldTeplateDocTemplate", "FieldTeplate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FieldTemplate>("smqdocModel.FieldTeplateDocTemplate", "FieldTeplate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="smqdocModel", Name="FieldTemplate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FieldTemplate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FieldTemplate object.
        /// </summary>
        /// <param name="fieldteplateid">Initial value of the fieldteplateid property.</param>
        /// <param name="fieldName">Initial value of the FieldName property.</param>
        /// <param name="filedType">Initial value of the FiledType property.</param>
        /// <param name="docTemplate_docteplateid">Initial value of the DocTemplate_docteplateid property.</param>
        /// <param name="orderNumber">Initial value of the OrderNumber property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static FieldTemplate CreateFieldTemplate(global::System.Int64 fieldteplateid, global::System.String fieldName, global::System.Int32 filedType, global::System.Int64 docTemplate_docteplateid, global::System.Int32 orderNumber, global::System.Int32 status)
        {
            FieldTemplate fieldTemplate = new FieldTemplate();
            fieldTemplate.fieldteplateid = fieldteplateid;
            fieldTemplate.FieldName = fieldName;
            fieldTemplate.FiledType = filedType;
            fieldTemplate.DocTemplate_docteplateid = docTemplate_docteplateid;
            fieldTemplate.OrderNumber = orderNumber;
            fieldTemplate.Status = status;
            return fieldTemplate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fieldteplateid
        {
            get
            {
                return _fieldteplateid;
            }
            set
            {
                if (_fieldteplateid != value)
                {
                    OnfieldteplateidChanging(value);
                    ReportPropertyChanging("fieldteplateid");
                    _fieldteplateid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fieldteplateid");
                    OnfieldteplateidChanged();
                }
            }
        }
        private global::System.Int64 _fieldteplateid;
        partial void OnfieldteplateidChanging(global::System.Int64 value);
        partial void OnfieldteplateidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FieldName
        {
            get
            {
                return _FieldName;
            }
            set
            {
                OnFieldNameChanging(value);
                ReportPropertyChanging("FieldName");
                _FieldName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FieldName");
                OnFieldNameChanged();
            }
        }
        private global::System.String _FieldName;
        partial void OnFieldNameChanging(global::System.String value);
        partial void OnFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FiledType
        {
            get
            {
                return _FiledType;
            }
            set
            {
                OnFiledTypeChanging(value);
                ReportPropertyChanging("FiledType");
                _FiledType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FiledType");
                OnFiledTypeChanged();
            }
        }
        private global::System.Int32 _FiledType;
        partial void OnFiledTypeChanging(global::System.Int32 value);
        partial void OnFiledTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Restricted
        {
            get
            {
                return _Restricted;
            }
            set
            {
                OnRestrictedChanging(value);
                ReportPropertyChanging("Restricted");
                _Restricted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Restricted");
                OnRestrictedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Restricted;
        partial void OnRestrictedChanging(Nullable<global::System.Boolean> value);
        partial void OnRestrictedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxVal
        {
            get
            {
                return _MaxVal;
            }
            set
            {
                OnMaxValChanging(value);
                ReportPropertyChanging("MaxVal");
                _MaxVal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxVal");
                OnMaxValChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxVal;
        partial void OnMaxValChanging(Nullable<global::System.Int32> value);
        partial void OnMaxValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinVal
        {
            get
            {
                return _MinVal;
            }
            set
            {
                OnMinValChanging(value);
                ReportPropertyChanging("MinVal");
                _MinVal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinVal");
                OnMinValChanged();
            }
        }
        private Nullable<global::System.Int32> _MinVal;
        partial void OnMinValChanging(Nullable<global::System.Int32> value);
        partial void OnMinValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DocTemplate_docteplateid
        {
            get
            {
                return _DocTemplate_docteplateid;
            }
            set
            {
                OnDocTemplate_docteplateidChanging(value);
                ReportPropertyChanging("DocTemplate_docteplateid");
                _DocTemplate_docteplateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DocTemplate_docteplateid");
                OnDocTemplate_docteplateidChanged();
            }
        }
        private global::System.Int64 _DocTemplate_docteplateid;
        partial void OnDocTemplate_docteplateidChanging(global::System.Int64 value);
        partial void OnDocTemplate_docteplateidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNumber
        {
            get
            {
                return _OrderNumber;
            }
            set
            {
                OnOrderNumberChanging(value);
                ReportPropertyChanging("OrderNumber");
                _OrderNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNumber");
                OnOrderNumberChanged();
            }
        }
        private global::System.Int32 _OrderNumber;
        partial void OnOrderNumberChanging(global::System.Int32 value);
        partial void OnOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "FieldTeplateDocTemplate", "DocTemplate")]
        public DocTemplate DocTemplate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocTemplate>("smqdocModel.FieldTeplateDocTemplate", "DocTemplate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocTemplate>("smqdocModel.FieldTeplateDocTemplate", "DocTemplate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DocTemplate> DocTemplateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocTemplate>("smqdocModel.FieldTeplateDocTemplate", "DocTemplate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DocTemplate>("smqdocModel.FieldTeplateDocTemplate", "DocTemplate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="smqdocModel", Name="UserAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserAccount object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="secondName">Initial value of the SecondName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="isAdmin">Initial value of the IsAdmin property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static UserAccount CreateUserAccount(global::System.Int32 userid, global::System.String login, global::System.String firstName, global::System.String secondName, global::System.String lastName, global::System.Int32 status, global::System.Boolean isAdmin, global::System.String password, global::System.String email)
        {
            UserAccount userAccount = new UserAccount();
            userAccount.userid = userid;
            userAccount.Login = login;
            userAccount.FirstName = firstName;
            userAccount.SecondName = secondName;
            userAccount.LastName = lastName;
            userAccount.Status = status;
            userAccount.IsAdmin = isAdmin;
            userAccount.Password = password;
            userAccount.Email = email;
            return userAccount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondName
        {
            get
            {
                return _SecondName;
            }
            set
            {
                OnSecondNameChanging(value);
                ReportPropertyChanging("SecondName");
                _SecondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondName");
                OnSecondNameChanged();
            }
        }
        private global::System.String _SecondName;
        partial void OnSecondNameChanging(global::System.String value);
        partial void OnSecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastAccess
        {
            get
            {
                return _LastAccess;
            }
            set
            {
                OnLastAccessChanging(value);
                ReportPropertyChanging("LastAccess");
                _LastAccess = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccess");
                OnLastAccessChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastAccess;
        partial void OnLastAccessChanging(Nullable<global::System.DateTime> value);
        partial void OnLastAccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "GroupManager", "UserGroup")]
        public EntityCollection<UserGroup> ManagedGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserGroup>("smqdocModel.GroupManager", "UserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserGroup>("smqdocModel.GroupManager", "UserGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "GroupUsers", "UserGroup")]
        public EntityCollection<UserGroup> MemberGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserGroup>("smqdocModel.GroupUsers", "UserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserGroup>("smqdocModel.GroupUsers", "UserGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="smqdocModel", Name="UserGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserGroup object.
        /// </summary>
        /// <param name="usergroupid">Initial value of the usergroupid property.</param>
        /// <param name="fullGroupName">Initial value of the FullGroupName property.</param>
        /// <param name="groupName">Initial value of the GroupName property.</param>
        /// <param name="managerid">Initial value of the Managerid property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static UserGroup CreateUserGroup(global::System.Int32 usergroupid, global::System.String fullGroupName, global::System.String groupName, global::System.Int32 managerid, global::System.Int32 status)
        {
            UserGroup userGroup = new UserGroup();
            userGroup.usergroupid = usergroupid;
            userGroup.FullGroupName = fullGroupName;
            userGroup.GroupName = groupName;
            userGroup.Managerid = managerid;
            userGroup.Status = status;
            return userGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usergroupid
        {
            get
            {
                return _usergroupid;
            }
            set
            {
                if (_usergroupid != value)
                {
                    OnusergroupidChanging(value);
                    ReportPropertyChanging("usergroupid");
                    _usergroupid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usergroupid");
                    OnusergroupidChanged();
                }
            }
        }
        private global::System.Int32 _usergroupid;
        partial void OnusergroupidChanging(global::System.Int32 value);
        partial void OnusergroupidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullGroupName
        {
            get
            {
                return _FullGroupName;
            }
            set
            {
                OnFullGroupNameChanging(value);
                ReportPropertyChanging("FullGroupName");
                _FullGroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullGroupName");
                OnFullGroupNameChanged();
            }
        }
        private global::System.String _FullGroupName;
        partial void OnFullGroupNameChanging(global::System.String value);
        partial void OnFullGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Managerid
        {
            get
            {
                return _Managerid;
            }
            set
            {
                OnManageridChanging(value);
                ReportPropertyChanging("Managerid");
                _Managerid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Managerid");
                OnManageridChanged();
            }
        }
        private global::System.Int32 _Managerid;
        partial void OnManageridChanging(global::System.Int32 value);
        partial void OnManageridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "GroupManager", "UserAccount")]
        public UserAccount Manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("smqdocModel.GroupManager", "UserAccount").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("smqdocModel.GroupManager", "UserAccount").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserAccount> ManagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserAccount>("smqdocModel.GroupManager", "UserAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserAccount>("smqdocModel.GroupManager", "UserAccount", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("smqdocModel", "GroupUsers", "UserAccount")]
        public EntityCollection<UserAccount> Members
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserAccount>("smqdocModel.GroupUsers", "UserAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserAccount>("smqdocModel.GroupUsers", "UserAccount", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
